version: "3.7"

services:
    zookeeper:
        build: docker/zookeeper
    kafka:
        build: docker/kafka
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
